version: "1.3"
services:
  pagermaid:
    image: mrwangzhe/pagermaid_modify
    restart: always
    container_name: "pagermaid"
    hostname: "pagermaid"
    #ports:
    #- "3333:3333"
    volumes:
    - ./:/pagermaid
